// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from './src/config/index.js';
import { defineConfig } from 'prisma/config';

export default defineConfig({
    schema: 'prisma/',
    migrations: {
        path: 'prisma/migrations',
    },
    datasource: {
        url: config.SUPABASE_DATABASE_URL,
    },
});
